### PR TITLE
Restructure project

### PR DESCRIPTION
**Pull request by EricMier**
+ Restructured project folder structure
+ Update TVL -> TSL
+ Added SIMDOperatos Lib
+ Column
+ Select operator
+ Unit tests (catch2)

### CODE REVIEW

**Comment by alexKrauseTUD** [comment]
Please fix the following issues:
* CMake configure breaks on simpleTest.cpp. Not all workstations have avx512. Please restructure to SSE for illustration or do not force the test to be built
* Rename datastructure to datastructures
* Correctly set the Licence Headers, as e.g. in filter.hpp. If files have been moved from our legacy MorphStore project, we shall also update the licence/disclaimer headers.
* Make the Catch2 tests to be optionally buildable

Why is there an additional SIMDOperators subdirectory in src? I feel this is not necessary, since the repository is already called like so and it seems to only add another layer of unnecessary indirection. The Library building can be handled by the toplevel CMakeLists.txt or are you planning on providing more, different libraries?

**Comment by JPietrzykTUD** [comment]
Please address the following issues:

- don't use unscoped `using namespace std;` (e.g., select.hpp)
- unify include-syntax (either #include "..." or #include <...>)
- why the detour of a nested friend class with private static methods and not just a nested struct?
- why do you pass single size_t parameters as const references?
- // reg_t position_vector = tsl::sequence<batchps>(); // TODO: check if sequence works correct --> Did it though?

Two general question:
> What is the actual purpose of the select class? Imho, the class is basically directly migrated from Morphstore, and it was okay-ish back then. However, we have already discussed the drawbacks of this design and came to the conclusion, that we only need the core, and the Metaoperator will do what your "select" does...


> Are you aware of the existence of **/operators/column_based/raw_data/filter.hpp**? Before implementing the select on your own, did you check, whether the code I wrote 11 months ago may work?

**Comment by EricMier** [comment]
> Please fix the following issues:
> 
>     * CMake configure breaks on simpleTest.cpp. Not all workstations have avx512. Please restructure to SSE for illustration or do not force the test to be built
> 
>     * Rename datastructure to datastructures
> 
>     * Correctly set the Licence Headers, as e.g. in filter.hpp. If files have been moved from our legacy MorphStore project, we shall also update the licence/disclaimer headers.
> 
>     * Make the Catch2 tests to be optionally buildable
> 
> 
> Why is there an additional SIMDOperators subdirectory in src? I feel this is not necessary, since the repository is already called like so and it seems to only add another layer of unnecessary indirection. The Library building can be handled by the toplevel CMakeLists.txt or are you planning on providing more, different libraries?

Hey Alex, regarding your issues:
1. It breaks on configure? How's that? During configuration phase nothing should be built.
2. Rename done (thanks Tom)
3. Done by JP (as far as I saw, thanks!)
4. There are only tests to be built, or am I wrong? If you want to use SIMDOperators, you link (from an outside project) against the lib interface SIMDOperators. You just don't use the other targets. But I could hide the test targets behind an ENABLE_TESTS flag.
5. The additional SIMDOperatos subdirectory serves the same purpose as a namespace in cpp. Since we are a header only lib, we have to set the src/ folder as an include path to our external target. That can lead to ambiguous includes. Take DAPHNE for example, where we also have an utils folder. If both contain a "Foo.hpp", the #include <utils/Foo.hpp> could not be resolved anymore, since the "daphne" target has to include daphne/src/ and SIMDOperators/src/, which both contain a utils/Foo.hpp.





> Please address the following issues:
> 
>     * don't use unscoped `using namespace std;` (e.g., select.hpp)
> 
>     * unify include-guards across all header files
> 
>     * unify include-syntax (either #include "..." or #include <...>)
> 
>     * why the detour of a nested friend class with private static methods and not just a nested struct?
> 
>     * why do you pass a single size_t parameters by const references?
> 
>     * // reg_t position_vector = tsl::sequence(); // TODO: check if sequence works correct --> Did it though?
> 
> 
> Two general question:
> 
> > What is the actual purpose of the select class? Imho, the class is basically directly migrated from Morphstore, and it was okay-ish back then. However, we have already discussed the drawbacks of this design and came to the conclusion, that we only need the core, and the Metaoperator will do what your "select" does...
> 
> > Are you aware of the existence of **/operators/column_based/raw_data/filter.hpp**? Before implementing the select on your own, did you check, whether the code I wrote 11 months ago may work?


Hey JP,

1. & 2. & 3. Done by Tom (thanks again)
3. It could make sense to not unify all includes, since "" prioritizes local files and <> system files (afaik)
4. Makes sense, just didn't thought about this.
5. You are right, doesn't make sense.
6. tsl::sequence() gave the sequence in the wrong order, therefore I used tsl::custom_sequence()


To your general Questions:
1. What are the drawbacks? I was not involved in this discussion. I also don't know what Metaoperator you are talking about.
2. I am aware, but as far as I remember it didn't build out of the box, so I didn't bother debugging, but implementing it myself.

**Comment by JPietrzykTUD** [comment]
"tsl::sequence() gave the sequence in the wrong order, therefore, I used tsl::custom_sequence()"
This is interesting and a super important and valuable insight. 
I would be highly delighted when all users of the TSL could report those functional issues (through a github issue, maybe) as soon as they stumble upon them. I will take care of it asap.

**Comment by JPietrzykTUD** [comment]
> @JPietrzykTUD regarding your last commit message:
> I can't reproduce that the submodule is cloned into tools/tvlgen. Did you try to remove all build files including CMakeCache?
> Or try 'git submodule update' in the project root folder. Maybe the submodule is not updated yet?
> 
> And pardon me for getting ill for the last 2 weeks(!!!)

I think the problem stems from the .gitmodules from the main branch.

**Comment by alexKrauseTUD** [comment]
> It breaks on configure? How's that? During configuration phase nothing should be built.

Sorry, I meant make. Typo by force of habit :)
My point was, that the example does not build out of the box on a standard workstation. Hence, I humbly requested a rewrite for SSE.

> There are only tests to be built, or am I wrong? If you want to use SIMDOperators, you link (from an outside project) against the lib interface SIMDOperators. You just don't use the other targets. But I could hide the test targets behind an ENABLE_TESTS flag.

I was distinguishing the how-to-use tests like the simpleTest.cpp and catch2 Tests. If I build via
`cmake -S . -B build && make -C build -j`
both will be built. I (mis)concepted, that you only used catch2 in one of the tests (operatorTest.cpp). I think we should unify the usage. But that can be performed in another PR.

Further, the current build (Branches SIMDOps: daphne TSLGen: main) fails with several errors:
* `SIMDOperators/test/column_based/raw_data/filter_test.cpp:3:10: fatal error: column.hpp: No such file or directory
    3 | #include <column.hpp>`
* `SIMDOperators/src/SIMDOperators/operators/select.hpp:74:83: error: ‘apply’ is not a member of ‘tsl::functors::greater_than<tsl::simd<long unsigned int, tsl::avx512>, tsl::workaround>’
   74 |                     mask_t mask = CompareOperator<batchps, tsl::workaround>::apply(data_vector, predicate_vector);`

**Comment by EricMier** [comment]
> > @JPietrzykTUD regarding your last commit message:
> > I can't reproduce that the submodule is cloned into tools/tvlgen. Did you try to remove all build files including CMakeCache?
> > Or try 'git submodule update' in the project root folder. Maybe the submodule is not updated yet?
> > And pardon me for getting ill for the last 2 weeks(!!!)
> 
> I think the problem stems from the .gitmodules from the main branch.

Ah I see. This should resolve when this PR is done.

**Comment by EricMier** [comment]
The project should now build using the default target "HelloTSL" following those steps:
~~~
$ rm -rf build
$ git submodule update --init --recursive
$ cmake -Bbuild .
$ cmake --build build --target HelloTSL
$ ./build/example/HelloTSL
~~~
Or simply use the build script:
~~~
$ ./build.sh -c -r
~~~
This cleans, builds and runs the default target.

To run the example using avx512 use
$ ./build.sh -r --avx512
Or substitute avx512 with sse, avx2 or neon. But there are missing primitives for sse. Neon is untested.

**Review by alexKrauseTUD — APPROVED** [review]
Code builds now and restructures the project as requested.

**Pull request merged**
